### ISSUE TITLE
Error inserting ZNS SSD kernel module

### ISSUE THREAD

**Issue by zy1024cs** [snu-csl/nvmevirt#6]
Hello, when I tried to enable CONFIG_NVMEVIRT_ZNS := y in the Makefile file and compiled it, the following error occurred when inserting the compiled file into the kernel module:
![image](https://user-images.githubusercontent.com/49134701/230249129-23d2c3be-0dbd-4d8b-9d3b-3fa4812adfc5.png)
My /etc/default/grub file settings are as follows:
![image](https://user-images.githubusercontent.com/49134701/230251858-0fb21cae-e1a9-4a51-840c-41123daba487.png)
May I ask what may be the reason? thank you

**Comment by arter97** [comment]
`sudo dmesg` (kernel log) will show more information.

Please post its output as well.

**Comment by zy1024cs** [comment]
If memmap_size is set to a multiple of 1024, such as 8192M, an errors may occur in zns_ftl.c. The details are as follows:
![image](https://user-images.githubusercontent.com/49134701/230536096-3cd0655c-ef22-42bc-9ae8-5655e7f3f73f.png)
Because **capacity** has been reduced by 1M in file main.c (The details are as follows), resulting in a value of 8191M.
![image](https://user-images.githubusercontent.com/49134701/230536361-5c278507-9057-4222-9588-c210acb51031.png)
When I try to set memmap_size to 8193M (8192+1) or 4097M (4096+1), this error will disappear, but another error will occur during insmod, like
![image](https://user-images.githubusercontent.com/49134701/230536604-a3ec54de-38e5-497c-8fd8-9ba9b7b77cb1.png)
Can you provide a suggested parameter that can make ZNS run? thank you

**Comment by euidong-lee** [comment]
In your dmesg, It shows "ns_size=16384MiB".
It means that you set memmap_size to 16385M(16384 + 1).
Since your machine has only 10GB memory, this may cause issues. 
Can you check memmap_size?

**Comment by euidong-lee** [comment]
Thanks to your help, we find memory corruption when accessing the struct zone_report.
Could you modify the code as follows and try it?
![캡처4](https://user-images.githubusercontent.com/88318253/231351764-28ddc376-3a73-4b8e-a29a-8b4bdc02589b.PNG)

We just use 'zonemode=zbd' option for fio. 
The other options are same for testing conventional ssds.
Please note that the write unit size for ZNS_PROTOTYPE is set to 128KB, due to the constraints of the prototype SSD that we used. So, the write request should be a multiple of 128KB. Also, write buffering is not supported in this prototype SSD, which means that write latency exposes the NAND program time.

**Comment by arter97** [comment]
@zy1024cs, please try out #7.

**Comment by arter97** [comment]
Linux kernel doesn't support ZNS without Zone Append capability.

Read this thread for context:
https://lore.kernel.org/all/20200818052936.10995-1-joshi.k@samsung.com/T/#u

If you don't use ZA, you can probably just fake NVMeVirt to report it's supported to make it R/W.
Try uncommenting this line: https://github.com/snu-csl/nvmevirt/pull/7/commits/96f21b9936f88800c2ab85e6eec2f824ccd5779a#diff-c714e0d9e04cd3a91b0e2de1c353296a3550544d3c5c63ff18f129f974beaa25R224

Ideally, it'd be nice if NVMeVirt adds support for ZA :upside_down_face:
